<?php
require_once __DIR__.'/../config/database.php';
require_once __DIR__.'/../includes/security.php';
$token=trim((string)($_GET['token']??$_POST['token']??''));
$error=false; $perfil=null;
if(!preg_match('/^[a-f0-9]{64}$/',$token)) $error=true;
if(!$error){$q=$pdo->prepare('SELECT c.id,c.usuario_id,p.correo,p.nombre,p.apellido FROM confirmaciones_correo c INNER JOIN perfiles_usuarios p ON p.usuario_id=c.usuario_id WHERE c.token_hash=? AND c.usado_en IS NULL AND c.expira_en>NOW() LIMIT 1');$q->execute([hash('sha256',$token)]);$perfil=$q->fetch();if(!$perfil)$error=true;}
if($_SERVER['REQUEST_METHOD']==='POST'&&!$error){if(!verificarCsrf($_POST['csrf_token']??null)){$error=true;}else{try{$pdo->beginTransaction();$q=$pdo->prepare('SELECT id,usuario_id FROM confirmaciones_correo WHERE token_hash=? AND usado_en IS NULL AND expira_en>NOW() LIMIT 1 FOR UPDATE');$q->execute([hash('sha256',$token)]);$r=$q->fetch();if(!$r)throw new RuntimeException('token_invalido');$pdo->prepare('UPDATE perfiles_usuarios SET confirmar_correo=1 WHERE usuario_id=?')->execute([$r['usuario_id']]);$pdo->prepare('UPDATE confirmaciones_correo SET usado_en=NOW() WHERE id=?')->execute([$r['id']]);$pdo->commit();header('Location: ../index.php?correo_confirmado=1');exit;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();emitirLogError('No se pudo confirmar el correo del analista.',['code'=>$e->getCode()]);$error=true;}}}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Confirmar correo</title><link rel="icon" href="../assets/img/logo.png"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet" integrity="sha384-tViUnnbYAV00FLIhhi3v/dWt3Jxw4gZQcNoSCxCIFNJVCx7/D55/wXsrNIRANwdD" crossorigin="anonymous"></head><body class="bg-light"><main class="container py-5"><div class="card shadow-sm mx-auto" style="max-width:620px"><div class="card-body p-4 text-center"><h1 class="h3 mb-3">Confirmación de correo</h1><?php if($error):?><div class="alert alert-danger">El enlace de confirmación es inválido, ya venció o ya fue utilizado.</div><a class="btn btn-success" href="../index.php">Ir al inicio de sesión</a><?php else:?><p>Confirma el correo <strong><?=htmlspecialchars($perfil['correo'],ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?></strong>.</p><form method="post"><?=csrf_field()?><input type="hidden" name="token" value="<?=htmlspecialchars($token,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')?>"><button class="btn btn-success" type="submit">Confirmar correo</button></form><?php endif;?></div></div></main></body></html>
