<?php
require_once __DIR__ . '/_layout.php'; requerirPermiso('departamentos.ver');
$deps=$pdo->query("SELECT d.*,COUNT(DISTINCT p.id_perfil) usuarios,COUNT(DISTINCT t.id_tickets) tickets FROM departamentos d LEFT JOIN perfiles_usuarios p ON p.departamento_id=d.id_departamentos LEFT JOIN tickets t ON t.departamento_id=d.id_departamentos GROUP BY d.id_departamentos ORDER BY d.nombre")->fetchAll();$pg=paginar($deps);$deps=$pg['items'];
adminLayoutStart('Departamentos');
?>
<div class="admin-page-head"><div><h2>Departamentos</h2><p>Oficinas, unidades solicitantes y estado de sus servicios.</p></div></div>
<div class="card-panel"><div class="table-responsive admin-departments-table-wrap"><table class="table align-middle admin-table admin-departments-table w-100 mb-0"><thead><tr><th>Departamento</th><th>Estado</th><th>Usuarios</th><th>Tickets</th><th class="text-end">Acción</th></tr></thead><tbody>
<?php foreach($deps as $d):?><tr><td><strong><?=h($d['nombre'])?></strong></td><td><span class="badge-admin <?=$d['estado']==='activo'?'badge-completado':'badge-pendiente'?>"><?=h(ucfirst($d['estado']))?></span></td><td><?=$d['usuarios']?></td><td><?=$d['tickets']?></td><td class="text-end"><form method="post" action="departamento_estado.php" class="d-inline"><?= csrf_field() ?><input type="hidden" name="id" value="<?=$d['id_departamentos']?>"><input type="hidden" name="estado" value="<?=$d['estado']==='activo'?'inactivo':'activo'?>"><button type="submit" class="btn btn-sm btn-light border" title="Cambiar estado"><i class="bi bi-power"></i></button></form></td></tr><?php endforeach;?>
<?php if(!$deps):?><tr><td colspan="5" class="text-center text-muted py-4">No hay departamentos registrados.</td></tr><?php endif;?></tbody></table></div><div class="admin-department-cards">
<?php foreach($deps as $d):?><article class="admin-department-card"><div><h3><?=h($d['nombre'])?></h3><span class="badge-admin <?=$d['estado']==='activo'?'badge-completado':'badge-pendiente'?>"><?=h(ucfirst($d['estado']))?></span><div class="small text-muted mt-1"><?=$d['usuarios']?> usuarios · <?=$d['tickets']?> tickets</div></div><form method="post" action="departamento_estado.php" class="d-inline"><?= csrf_field() ?><input type="hidden" name="id" value="<?=$d['id_departamentos']?>"><input type="hidden" name="estado" value="<?=$d['estado']==='activo'?'inactivo':'activo'?>"><button type="submit" class="btn btn-sm btn-light border" title="Cambiar estado"><i class="bi bi-power"></i></button></form></article><?php endforeach;?>
</div><?=renderPaginacion($pg)?></div>
<?php adminLayoutEnd(); ?>
