<?php
require_once __DIR__ . '/_layout.php'; requerirPermiso('hojas.ver');
$where=[];$params=[];
if(($_GET['periodo']??'')==='mes'){$where[]="YEAR(h.fecha)=YEAR(CURDATE()) AND MONTH(h.fecha)=MONTH(CURDATE())";}
if(!empty($_GET['tecnico_id'])){$where[]='h.tecnico_id=?';$params[]=(int)$_GET['tecnico_id'];}
if(!empty($_GET['estatus'])){$where[]='h.estatus=?';$params[]=$_GET['estatus'];}
$sql="SELECT h.*,d.nombre departamento,COALESCE(CONCAT(p.nombre,' ',p.apellido),u.usuario) tecnico, t.id_tickets ticket
FROM hojas_servicio h JOIN departamentos d ON d.id_departamentos=h.departamento_solicitante_id JOIN usuarios u ON u.id_usuarios=h.tecnico_id LEFT JOIN perfiles_usuarios p ON p.usuario_id=u.id_usuarios LEFT JOIN tickets t ON t.id_tickets=h.ticket_id";
if($where)$sql.=" WHERE ".implode(' AND ',$where);$sql.=" ORDER BY h.fecha DESC,h.id_hojas DESC";
$s=$pdo->prepare($sql);$s->execute($params);$rows=$s->fetchAll();$pg=paginar($rows);$rows=$pg['items'];$tecs=$pdo->query("SELECT u.id_usuarios,COALESCE(CONCAT(p.nombre,' ',p.apellido),u.usuario) nombre FROM usuarios u LEFT JOIN perfiles_usuarios p ON p.usuario_id=u.id_usuarios JOIN roles r ON r.id_roles=u.rol_id WHERE r.nombre='analista' ORDER BY nombre")->fetchAll();
adminLayoutStart('Hojas de servicio');
?>
<div class="admin-page-head"><div><h2>Hojas de servicio</h2><p>Consulta institucional de los servicios ejecutados.</p></div></div>
<div class="card-panel mb-3"><div class="panel-body"><form class="row g-2"><div class="col-md-4"><select name="tecnico_id" class="form-select form-select-sm"><option value="">Todos los analistas</option><?php foreach($tecs as $t):?><option value="<?=$t['id_usuarios']?>" <?=((string)$t['id_usuarios']==($_GET['tecnico_id']??''))?'selected':''?>><?=h($t['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-3"><select name="estatus" class="form-select form-select-sm"><option value="">Todos los estados</option><option value="completado">Completado</option><option value="en_proceso">En proceso</option><option value="pendiente_insumos">Pendiente por insumos</option></select></div><div class="col-md-3"><button class="btn btn-brand btn-sm w-100">Filtrar</button></div><div class="col-md-2"><a class="btn btn-outline-brand btn-sm w-100" href="hojas.php">Limpiar</a></div></form></div></div>
<div class="card-panel"><div class="table-responsive admin-sheet-table-wrap"><table class="table admin-table align-middle mb-0"><thead><tr><th>Hoja</th><th>Fecha</th><th>Analista</th><th>Departamento</th><th>Estado</th><th>Tiempo</th><th>Atendido</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><strong><?=numeroHoja((int)$r['id_hojas'])?></strong></td><td><?=date('d/m/Y',strtotime($r['fecha']))?></td><td><?=h($r['tecnico'])?></td><td><?=h($r['departamento'])?></td><td><span class="badge-admin <?= $r['estatus']==='completado'?'badge-completado':($r['estatus']==='en_proceso'?'badge-proceso':'badge-pendiente')?>"><?=h(ucwords(str_replace('_',' ',$r['estatus'])))?></span></td><td><?=minutosATexto($r['tiempo_total_minutos']!==null?(int)$r['tiempo_total_minutos']:null)?></td><td><?=h($r['usuario_atendido_nombre'])?></td><td><a class="btn btn-sm btn-light border" href="ver_hoja.php?id=<?=$r['id_hojas']?>" title="Ver hoja"><i class="bi bi-eye"></i></a></td></tr><?php endforeach;?></tbody></table></div>
<div class="admin-mobile-cards">
<?php foreach($rows as $r):?><article class="ticket-card admin-mobile-card"><div class="ticket-stub <?= $r['estatus']==='completado'?'st-completado':($r['estatus']==='en_proceso'?'st-proceso':'st-pendiente') ?>"><span>N° <?=numeroHoja((int)$r['id_hojas'])?></span></div><div class="ticket-body"><div class="t-top"><p class="t-title mb-1"><?=h($r['tecnico'])?></p><span class="badge-admin <?= $r['estatus']==='completado'?'badge-completado':($r['estatus']==='en_proceso'?'badge-proceso':'badge-pendiente')?>"><?=h(ucwords(str_replace('_',' ',$r['estatus'])))?></span></div><div class="t-meta"><?=h($r['departamento'])?> · <?=h($r['usuario_atendido_nombre'])?></div><div class="t-meta d-flex justify-content-between align-items-center gap-2"><span><i class="bi bi-calendar3 me-1"></i><?=date('d/m/Y',strtotime($r['fecha']))?> · <?=minutosATexto($r['tiempo_total_minutos']!==null?(int)$r['tiempo_total_minutos']:null)?></span><a class="btn btn-sm btn-light border" href="ver_hoja.php?id=<?=$r['id_hojas']?>" title="Ver hoja"><i class="bi bi-eye"></i></a></div></div></article><?php endforeach;?>
</div><?=renderPaginacion($pg)?></div>
<?php adminLayoutEnd(); ?>
