<?php
require_once __DIR__ . '/_layout.php'; requerirPermiso('seguridad.ver');
$online=$pdo->query("SELECT u.id_usuarios,u.usuario,COALESCE(CONCAT(p.nombre,' ',p.apellido),u.usuario) nombre,r.nombre rol,u.ultima_actividad FROM usuarios u JOIN roles r ON r.id_roles=u.rol_id LEFT JOIN perfiles_usuarios p ON p.usuario_id=u.id_usuarios WHERE u.estado='activo' AND u.ultima_actividad IS NOT NULL AND u.ultima_actividad >= DATE_SUB(NOW(),INTERVAL 15 MINUTE) ORDER BY u.ultima_actividad DESC")->fetchAll();$totalOnline=count($online);$pg=paginar($online);$online=$pg['items'];
$failed=0;
adminLayoutStart('Seguridad');
?>
<div class="admin-page-head"><div><h2>Seguridad</h2><p>Estado de cuentas, sesiones recientes y controles de acceso.</p></div></div>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="kpi-card"><div class="kpi-icon admin-tone-green"><i class="bi bi-shield-check"></i></div><div class="kpi-label mt-2">Sesiones activas</div><div class="kpi-value"><?=$totalOnline?></div></div></div><div class="col-md-4"><div class="kpi-card"><div class="kpi-icon admin-tone-teal"><i class="bi bi-person-lock"></i></div><div class="kpi-label mt-2">Cuentas activas</div><div class="kpi-value"><?=$pdo->query("SELECT COUNT(*) FROM usuarios WHERE estado='activo'")->fetchColumn()?></div></div></div><div class="col-md-4"><div class="kpi-card"><div class="kpi-icon admin-tone-red"><i class="bi bi-person-x"></i></div><div class="kpi-label mt-2">Cuentas inactivas</div><div class="kpi-value"><?=$pdo->query("SELECT COUNT(*) FROM usuarios WHERE estado='inactivo'")->fetchColumn()?></div></div></div></div>
<div class="card-panel"><div class="panel-head"><h2>Usuarios activos recientemente</h2></div><div class="table-responsive admin-security-table-wrap"><table class="table admin-table mb-0"><thead><tr><th>Usuario</th><th>Rol</th><th>Última actividad</th></tr></thead><tbody><?php foreach($online as $r):?><tr><td><?=h($r['nombre'])?> <small class="text-success">●</small></td><td><?=h(ucfirst($r['rol']))?></td><td><?=date('d/m/Y H:i:s',strtotime($r['ultima_actividad']))?></td></tr><?php endforeach;?></tbody></table></div><div class="admin-security-cards">
<?php foreach($online as $r):?><article><div class="d-flex justify-content-between gap-2"><strong><?=h($r['nombre'])?> <small class="text-success">●</small></strong><span class="badge-admin badge-role"><?=h(ucfirst($r['rol']))?></span></div><div class="small text-muted mt-1"><i class="bi bi-clock me-1"></i><?=date('d/m/Y H:i:s',strtotime($r['ultima_actividad']))?></div></article><?php endforeach;?>
</div><?=renderPaginacion($pg)?></div>
<div class="alert alert-info mt-3"><i class="bi bi-info-circle me-1"></i>Las sesiones activas se determinan por actividad registrada durante los últimos 15 minutos.</div>
<?php adminLayoutEnd(); ?>
