<?php
require_once __DIR__ . '/_layout.php'; requerirPermiso('tickets.ver');
$where=[];$params=[];
if(!empty($_GET['estado'])){$where[]='t.estado=?';$params[]=$_GET['estado'];}
if(!empty($_GET['departamento_id'])){$where[]='t.departamento_id=?';$params[]=(int)$_GET['departamento_id'];}
$sql="SELECT t.*,d.nombre departamento,COALESCE(CONCAT(ps.nombre,' ',ps.apellido),us.usuario) solicitante,COALESCE(CONCAT(pa.nombre,' ',pa.apellido),ua.usuario,'Sin asignar') analista
FROM tickets t JOIN departamentos d ON d.id_departamentos=t.departamento_id JOIN usuarios us ON us.id_usuarios=t.solicitante_id LEFT JOIN perfiles_usuarios ps ON ps.usuario_id=us.id_usuarios LEFT JOIN usuarios ua ON ua.id_usuarios=t.analista_id LEFT JOIN perfiles_usuarios pa ON pa.usuario_id=ua.id_usuarios";
if($where)$sql.=" WHERE ".implode(" AND ",$where);$sql.=" ORDER BY t.fecha_creacion DESC";
$s=$pdo->prepare($sql);$s->execute($params);$rows=$s->fetchAll();$pg=paginar($rows);$rows=$pg['items'];$deps=$pdo->query("SELECT * FROM departamentos ORDER BY nombre")->fetchAll();
adminLayoutStart('Tickets');
?>
<div class="admin-page-head"><div><h2>Tickets</h2><p>Supervisión global de solicitudes y estados de atención.</p></div></div>
<div class="card-panel mb-3"><div class="panel-body"><form class="row g-2"><div class="col-md-4"><select name="estado" class="form-select form-select-sm"><option value="">Todos los estados</option><?php foreach(['pendiente','asignado','en_proceso','completado','cancelado'] as $e):?><option <?=$e===($_GET['estado']??'')?'selected':''?> value="<?=$e?>"><?=h(ucwords(str_replace('_',' ',$e)))?></option><?php endforeach;?></select></div><div class="col-md-5"><select name="departamento_id" class="form-select form-select-sm"><option value="">Todos los departamentos</option><?php foreach($deps as $d):?><option value="<?=$d['id_departamentos']?>" <?=((string)$d['id_departamentos']==($_GET['departamento_id']??''))?'selected':''?>><?=h($d['nombre'])?></option><?php endforeach;?></select></div><div class="col-md-3"><button class="btn btn-brand btn-sm w-100">Filtrar</button></div></form></div></div>
<div class="card-panel"><div class="table-responsive admin-ticket-table-wrap"><table class="table admin-table align-middle mb-0"><thead><tr><th>#</th><th>Título</th><th>Departamento</th><th>Solicitante</th><th>Analista</th><th>Estado</th><th>Fecha</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td>#<?=$r['id_tickets']?></td><td><strong><?=h($r['titulo'])?></strong><div class="small text-muted"><?=h(mb_strimwidth($r['descripcion'],0,90,'…'))?></div></td><td><?=h($r['departamento'])?></td><td><?=h($r['solicitante'])?></td><td><?=h($r['analista'])?></td><td><span class="badge-admin badge-<?=h($r['estado'])?>"><?=h(ucwords(str_replace('_',' ',$r['estado'])))?></span></td><td><?=date('d/m/Y H:i',strtotime($r['fecha_creacion']))?></td></tr><?php endforeach;?></tbody></table></div>
<div class="admin-mobile-cards">
<?php foreach($rows as $r):?><article class="ticket-card admin-mobile-card"><div class="ticket-stub <?= $r['estado']==='completado'?'st-completado':($r['estado']==='en_proceso'?'st-proceso':'st-pendiente') ?>"><span>#<?=$r['id_tickets']?></span></div><div class="ticket-body"><div class="t-top"><p class="t-title mb-1"><?=h($r['titulo'])?></p><span class="badge-admin badge-<?=h($r['estado'])?>"><?=h(ucwords(str_replace('_',' ',$r['estado'])))?></span></div><div class="t-meta"><?=h($r['departamento'])?> · <?=h($r['solicitante'])?></div><div class="t-meta d-flex justify-content-between gap-2 flex-wrap"><span><i class="bi bi-person me-1"></i><?=h($r['analista'])?> · <i class="bi bi-calendar3 me-1"></i><?=date('d/m/Y H:i',strtotime($r['fecha_creacion']))?></span></div></div></article><?php endforeach;?>
</div><?=renderPaginacion($pg)?></div>
<?php adminLayoutEnd(); ?>
